version: '3'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

volumes:
  mew_data:

